export type ClaimType =
  | "DATA"
  | "METHOD"
  | "AI_CHOICE"
  | "USER_CHOICE"
  | "INFERENCE"
  | "HYPOTHESIS"
  | "UNSUPPORTED";

export type ClaimStatus =
  | "SUPPORTED"
  | "SUPPORTED_WITH_LIMITATIONS"
  | "HYPOTHESIS"
  | "INSUFFICIENT_SUPPORT";

export type Claim = {
  id: string;
  text: string;
  type: ClaimType;
  status: ClaimStatus;
  source: string;
  warning?: string;
  evidence: Record<string, number | "NA">;
};

export type MethodCard = {
  slug: string;
  name: string;
  package: string;
  fn: string;
  category: string;
  status: "VERIFIED" | "REVIEW_REQUIRED";
  question: string;
  notAnswered: string[];
  appropriate: string[];
  assumptions: string[];
  failureModes: string[];
  alternatives: string[];
  validation: string[];
  officialDocumentation?: string;
  versionNote?: string;
  origin?: "BUILT_IN" | "CUSTOM";
};

export const claims: Claim[] = [
  {
    id: "CLM-004",
    text: "Exposure_A and Clinical_Score are associated with a similar molecular expression pattern.",
    type: "INFERENCE",
    status: "SUPPORTED_WITH_LIMITATIONS",
    source: "Comparison of Analysis 01 and Analysis 02",
    warning: "Exposure_A was not included in the Clinical_Score model.",
    evidence: {
      Provenance: 2,
      "Statistical appropriateness": 2,
      "Multiple testing": 2,
      Robustness: 1,
      "Held-out validation": 1,
      "Independent support": 1,
      "External replication": 0,
      "Confounding resolution": 1,
    },
  },
  {
    id: "CLM-003",
    text: "Cell_State_C genes are collectively shifted upward with increasing Continuous_Trait.",
    type: "DATA",
    status: "SUPPORTED",
    source: "Analysis 03 · cameraPR result",
    warning: "Gene-set enrichment does not establish measured cell abundance.",
    evidence: {
      Provenance: 2,
      "Statistical appropriateness": 2,
      "Multiple testing": 2,
      Robustness: 1,
      "Held-out validation": "NA",
      "Independent support": 0,
      "External replication": 0,
      "Confounding resolution": 2,
    },
  },
  {
    id: "CLM-002",
    text: "The Exposure_A molecular score reproduces the exposure in held-out synthetic participants.",
    type: "DATA",
    status: "SUPPORTED",
    source: "Analysis 04 · repeated 5-fold cross-validation",
    warning: "Predictive performance does not establish biological mechanism.",
    evidence: {
      Provenance: 2,
      "Statistical appropriateness": 2,
      "Multiple testing": 2,
      Robustness: 2,
      "Held-out validation": 2,
      "Independent support": 0,
      "External replication": 0,
      "Confounding resolution": 1,
    },
  },
  {
    id: "CLM-001",
    text: "Exposure_A may contribute to the molecular association observed with Clinical_Score.",
    type: "HYPOTHESIS",
    status: "HYPOTHESIS",
    source: "Researcher-authored interpretation",
    warning: "This explanation requires targeted confounder analysis and independent validation.",
    evidence: {
      Provenance: 2,
      "Statistical appropriateness": 1,
      "Multiple testing": 2,
      Robustness: 0,
      "Held-out validation": "NA",
      "Independent support": 0,
      "External replication": 0,
      "Confounding resolution": 0,
    },
  },
];

export const methods: MethodCard[] = [
  {
    slug: "limma-voom",
    name: "limma-voom",
    package: "limma",
    fn: "voom + lmFit",
    category: "Differential expression",
    status: "VERIFIED",
    question: "Which features show evidence of association with a modeled exposure or outcome after specified covariate adjustment?",
    notAnswered: ["Causality", "Biological mechanism", "Temporal progression"],
    appropriate: ["RNA-seq counts with replicated samples", "User-approved linear design matrices"],
    assumptions: ["Design matrix is correctly specified", "Mean–variance trend is adequately modeled", "Samples are independent unless explicitly modeled"],
    failureModes: ["Unmodeled batch effects", "Confounded or rank-deficient design", "Silent sample misalignment"],
    alternatives: ["edgeR quasi-likelihood", "DESeq2"],
    validation: ["Inspect mean–variance trend", "Review design rank", "Run covariate sensitivity analysis"],
  },
  {
    slug: "camera-pr",
    name: "cameraPR",
    package: "limma",
    fn: "cameraPR",
    category: "Gene-set testing",
    status: "VERIFIED",
    question: "Are genes in a predefined set more strongly associated with a phenotype than genes outside the set?",
    notAnswered: ["Measured cell proportions", "Causality", "Whether every gene in the set changes"],
    appropriate: ["Genome-wide signed statistics", "Predefined, independently constructed gene sets"],
    assumptions: ["Gene universe is appropriate", "Gene identifiers are matched correctly", "Inter-gene correlation is considered"],
    failureModes: ["Circular gene-set construction", "Biased gene universe", "Treating enrichment as abundance"],
    alternatives: ["camera", "roast", "fry", "rank-based enrichment"],
    validation: ["Audit set provenance", "Vary the gene universe", "Compare against an alternative test"],
  },
  {
    slug: "filter-by-expr",
    name: "filterByExpr",
    package: "edgeR",
    fn: "filterByExpr",
    category: "Expression filtering",
    status: "VERIFIED",
    question: "Which genes have sufficient expression, given the experimental design, to retain for downstream modeling?",
    notAnswered: ["Which genes are associated", "Biological importance"],
    appropriate: ["Raw count matrices", "A defined design or grouping variable"],
    assumptions: ["Library sizes are meaningful", "The design reflects minimum group structure"],
    failureModes: ["Filtering after outcome inspection", "Incorrect grouping", "Discarding filter provenance"],
    alternatives: ["Pre-specified CPM threshold"],
    validation: ["Report retained feature count", "Record threshold parameters"],
  },
  {
    slug: "bh-fdr",
    name: "Benjamini–Hochberg FDR",
    package: "stats",
    fn: "p.adjust(method='BH')",
    category: "Multiple testing",
    status: "VERIFIED",
    question: "Which results remain supported while controlling the expected false discovery rate within a declared test family?",
    notAnswered: ["Practical importance", "Replication", "Absence of any effect when non-significant"],
    appropriate: ["A clearly defined family of simultaneous tests"],
    assumptions: ["The FDR family is declared", "P-values are valid for their individual tests"],
    failureModes: ["Splitting test families post hoc", "Reporting raw p-values as adjusted", "Treating FDR as replication"],
    alternatives: ["Bonferroni FWER", "Independent hypothesis weighting"],
    validation: ["Export all raw and adjusted p-values", "Inspect the declared testing family"],
  },
  {
    slug: "cross-validation",
    name: "Repeated K-fold cross-validation",
    package: "workflow",
    fn: "controlled_cv",
    category: "Validation",
    status: "REVIEW_REQUIRED",
    question: "How well does a fixed modeling pipeline generalize to held-out samples from the same sampling context?",
    notAnswered: ["External cohort replication", "Causality", "Mechanism"],
    appropriate: ["Prediction objectives with adequate sample size", "Pipelines where every learned step can be folded"],
    assumptions: ["Folds respect dependence structure", "All data-dependent operations occur inside training folds"],
    failureModes: ["Feature selection before splitting", "Full-dataset scaling", "Tuning on held-out folds"],
    alternatives: ["Nested cross-validation", "Independent external validation"],
    validation: ["Run deterministic leakage checks", "Store fold hashes", "Use an untouched external dataset when available"],
  },
  {
    slug: "edger-quasi-likelihood",
    name: "edgeR quasi-likelihood",
    package: "edgeR",
    fn: "glmQLFit + glmQLFTest",
    category: "Differential expression",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "Which genes show evidence of differential expression under a negative-binomial GLM while accounting for uncertainty in gene-wise dispersion?",
    notAnswered: ["Causality", "Biological mechanism", "Whether an omitted covariate explains the association"],
    appropriate: ["Raw RNA-seq counts with biological replication", "Multi-factor designs expressed by a full-rank design matrix"],
    assumptions: ["Counts follow an adequate negative-binomial mean–variance model", "The design and contrasts encode the intended question", "Library composition normalization is appropriate"],
    failureModes: ["Confounded or rank-deficient design", "Incorrect contrast direction", "Using normalized non-count input", "Ignoring low-count filtering"],
    alternatives: ["limma-voom", "DESeq2 Wald test", "edgeR likelihood-ratio test"],
    validation: ["Inspect MDS and dispersion trends", "Audit design rank and contrasts", "Compare with an alternative count-aware workflow"],
    officialDocumentation: "https://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf",
  },
  {
    slug: "deseq2-wald",
    name: "DESeq2 Wald test",
    package: "DESeq2",
    fn: "DESeq + results",
    category: "Differential expression",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "For a specified model coefficient or contrast, which genes show evidence that the corresponding negative-binomial GLM effect differs from zero?",
    notAnswered: ["Causality", "A global multi-level effect unless a suitable contrast is defined", "External reproducibility"],
    appropriate: ["Integer count matrices with replicated samples", "Pre-specified pairwise or coefficient-level hypotheses"],
    assumptions: ["Size-factor normalization is suitable", "Dispersion modeling is adequate", "The design is full rank and sample annotations are aligned"],
    failureModes: ["Ambiguous reference levels", "Interpreting shrunken fold changes as different tests", "Inappropriate independent filtering", "No biological replication"],
    alternatives: ["edgeR quasi-likelihood", "limma-voom", "DESeq2 likelihood-ratio test"],
    validation: ["Record resultsNames and contrast definition", "Inspect dispersion and MA plots", "Separate hypothesis testing from effect-size shrinkage"],
    officialDocumentation: "https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html",
  },
  {
    slug: "deseq2-lrt",
    name: "DESeq2 likelihood-ratio test",
    package: "DESeq2",
    fn: "DESeq(test='LRT')",
    category: "Differential expression",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "Does a full negative-binomial model explain a gene better than a declared reduced model?",
    notAnswered: ["Which individual coefficient caused a multi-degree-of-freedom result", "Pairwise effects unless separately tested", "Causality"],
    appropriate: ["Time-course, interaction, or multi-level questions comparing nested models", "Integer RNA-seq count data"],
    assumptions: ["Full and reduced models are nested", "Terms retained in the reduced model represent intended adjustment", "Dispersion and size-factor models are adequate"],
    failureModes: ["Non-nested model comparison", "Attributing an omnibus result to one level", "Dropping nuisance covariates from the reduced model"],
    alternatives: ["DESeq2 Wald test", "edgeR quasi-likelihood multi-coefficient test", "limma moderated F-test"],
    validation: ["Display full and reduced formulas side by side", "Record degrees of freedom", "Follow with pre-specified coefficient tests where justified"],
    officialDocumentation: "https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#likelihood-ratio-test",
  },
  {
    slug: "limma-camera",
    name: "camera",
    package: "limma",
    fn: "camera",
    category: "Gene-set testing",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "Are genes in a predefined set more differentially expressed than genes outside the set while accounting for inter-gene correlation?",
    notAnswered: ["Whether the set is changed in an absolute self-contained sense", "Cell abundance", "Causality"],
    appropriate: ["Competitive testing of many predefined gene sets", "Expression data with a design matrix and contrast"],
    assumptions: ["The gene universe is appropriate", "Gene sets were defined independently", "The design and contrast are valid"],
    failureModes: ["Circular gene-set construction", "Biased universe", "Confusing competitive and self-contained hypotheses"],
    alternatives: ["cameraPR", "roast", "fgsea"],
    validation: ["Audit the gene universe and set provenance", "Check identifier matching", "Compare a complementary gene-set hypothesis"],
    officialDocumentation: "https://bioconductor.org/packages/release/bioc/vignettes/limma/inst/doc/usersguide.pdf",
  },
  {
    slug: "limma-roast",
    name: "ROAST",
    package: "limma",
    fn: "roast + mroast",
    category: "Gene-set testing",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "Does a predefined gene set show evidence of differential expression as a self-contained hypothesis?",
    notAnswered: ["Whether the set is more changed than genes outside it", "Measured cell proportions", "Biological mechanism"],
    appropriate: ["A focused number of gene sets of prior interest", "Designs requiring rotation-based inference"],
    assumptions: ["The expression model and contrast are valid", "The set is defined independently", "Rotation inference is suitable for the design"],
    failureModes: ["Testing thousands of post-hoc sets without a declared family", "Confusing self-contained and competitive results", "Overinterpreting directional summaries"],
    alternatives: ["camera", "cameraPR", "fgsea"],
    validation: ["Declare the testing family", "Inspect set size and membership", "Compare against a competitive test"],
    officialDocumentation: "https://bioconductor.org/packages/release/bioc/vignettes/limma/inst/doc/usersguide.pdf",
  },
  {
    slug: "fgsea-preranked",
    name: "fgseaMultilevel",
    package: "fgsea",
    fn: "fgseaMultilevel",
    category: "Gene-set testing",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "Are members of a predefined pathway concentrated near an extreme of a ranked genome-wide statistic?",
    notAnswered: ["Causality", "Measured abundance", "Independence from the ranking analysis"],
    appropriate: ["A named genome-wide ranking statistic", "Predefined pathways with explicit size limits"],
    assumptions: ["Ranking statistics have a defensible direction", "Gene identifiers are unique and matched", "Pathway construction is independent"],
    failureModes: ["Duplicate or tied identifiers handled silently", "Ranking only selected genes", "Using post-hoc pathways", "Ignoring pathway-size filters"],
    alternatives: ["cameraPR", "camera", "ROAST"],
    validation: ["Retain the full ranking universe", "Record minSize, maxSize, and score exponent", "Inspect leading-edge stability"],
    officialDocumentation: "https://bioconductor.org/packages/release/bioc/vignettes/fgsea/inst/doc/fgsea-tutorial.html",
  },
  {
    slug: "dream-repeated-measures",
    name: "dream repeated-measures model",
    package: "variancePartition",
    fn: "voomWithDreamWeights + dream",
    category: "Repeated measures",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "Which genes are associated with fixed effects when repeated measurements or multiple random effects induce sample dependence?",
    notAnswered: ["Causality", "Whether a random-effect structure is scientifically necessary", "External generalization"],
    appropriate: ["RNA-seq with repeated measurements", "Designs requiring one or more defensible random effects"],
    assumptions: ["Random-effect structure reflects the sampling design", "Sufficient independent units exist", "Mean–variance weights and mixed-model approximations are adequate"],
    failureModes: ["Random effects with too few levels", "Over-specified random structure", "Treating technical replicates as independent", "Convergence failures ignored"],
    alternatives: ["limma duplicateCorrelation", "Subject fixed effects", "edgeR with an appropriate block design"],
    validation: ["Review variance components", "Inspect convergence and singular fits", "Compare with a scientifically defensible fixed-effect formulation"],
    officialDocumentation: "https://bioconductor.org/packages/release/bioc/vignettes/variancePartition/inst/doc/dream.html",
  },
  {
    slug: "surrogate-variable-analysis",
    name: "Surrogate variable analysis",
    package: "sva",
    fn: "svaseq + sva",
    category: "Unwanted variation",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "Can latent sources of unwanted variation be estimated as surrogate variables for inclusion in a high-dimensional model?",
    notAnswered: ["The biological identity of a latent factor", "Causality", "Whether every estimated surrogate variable should be adjusted"],
    appropriate: ["High-dimensional assays with plausible unmodeled variation", "A clearly declared full and null model"],
    assumptions: ["The protected biological signal is encoded correctly", "Latent variation can be estimated from the assay", "Adjustment does not remove the effect of interest"],
    failureModes: ["Leakage in predictive evaluation", "Removing biological signal", "Choosing surrogate-variable count post hoc", "Using inconsistent full and null models"],
    alternatives: ["Measured batch covariates", "RUV methods", "variancePartition"],
    validation: ["Check association with known technical factors", "Run sensitivity to surrogate-variable count", "Keep estimation inside training folds for prediction"],
    officialDocumentation: "https://bioconductor.org/packages/release/bioc/vignettes/sva/inst/doc/sva.pdf",
  },
  {
    slug: "combat-seq",
    name: "ComBat-seq",
    package: "sva",
    fn: "ComBat_seq",
    category: "Batch adjustment",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "Can known batch effects be adjusted in RNA-seq raw counts using a negative-binomial regression model?",
    notAnswered: ["Whether batch is separable from biology", "Causality", "Whether adjusted counts are suitable for every downstream method"],
    appropriate: ["Known batch labels in raw RNA-seq counts", "Designs where biological groups are not completely confounded with batch"],
    assumptions: ["Batch labels are correct", "Biological variables to preserve are specified", "There is overlap across batch and biology"],
    failureModes: ["Perfect batch–group confounding", "Applying to normalized continuous values", "Treating adjusted counts as raw observations", "Using adjustment before data splitting"],
    alternatives: ["Batch as a model covariate", "Surrogate variable analysis", "RUV approaches"],
    validation: ["Inspect batch–biology contingency", "Compare direct covariate adjustment", "Re-run downstream sensitivity without transformed counts"],
    officialDocumentation: "https://bioconductor.org/packages/release/bioc/manuals/sva/man/sva.pdf",
  },
  {
    slug: "spearman-correlation",
    name: "Spearman correlation",
    package: "stats",
    fn: "cor.test(method='spearman')",
    category: "Association",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "Is there evidence of a monotonic association between two paired variables?",
    notAnswered: ["Causality", "Mediation", "A covariate-adjusted association without an extended model"],
    appropriate: ["Ordinal or continuous paired measurements", "Monotonic relationships where linearity is not required"],
    assumptions: ["Pairs are correctly aligned", "Observations are independent", "Ties and missing values are handled explicitly"],
    failureModes: ["Confounding ignored", "Repeated measurements treated as independent", "Multiple correlations without correction", "Correlation interpreted as agreement"],
    alternatives: ["Pearson correlation", "Kendall correlation", "Linear regression", "Partial correlation"],
    validation: ["Plot the paired data", "Inspect influential observations", "Correct the declared multiple-testing family"],
    officialDocumentation: "https://stat.ethz.ch/R-manual/R-devel/library/stats/html/cor.test.html",
  },
  {
    slug: "linear-regression",
    name: "Linear regression",
    package: "stats",
    fn: "lm",
    category: "Association",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "How is a continuous outcome associated with specified predictors under a linear conditional-mean model?",
    notAnswered: ["Causality without a causal design", "Nonlinear effects unless modeled", "Robustness to omitted confounding"],
    appropriate: ["Continuous outcomes", "Pre-specified predictors and covariates"],
    assumptions: ["Conditional mean is adequately modeled", "Residual variance and dependence are addressed", "Influential observations are evaluated"],
    failureModes: ["Nonlinearity", "Heteroskedasticity", "Dependent observations", "Multicollinearity", "Outcome leakage"],
    alternatives: ["Robust regression", "Generalized additive model", "Linear mixed model"],
    validation: ["Inspect residuals and influence", "Check design rank", "Assess nonlinear and heteroskedastic sensitivity"],
    officialDocumentation: "https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html",
  },
  {
    slug: "logistic-regression",
    name: "Logistic regression",
    package: "stats",
    fn: "glm(family=binomial)",
    category: "Association",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "How are specified predictors associated with the log-odds of a binary outcome?",
    notAnswered: ["Causality", "Absolute risk transportability", "Mechanism"],
    appropriate: ["Binary outcomes", "A pre-specified linear predictor with adequate events"],
    assumptions: ["Observations are independent or dependence is modeled", "Continuous predictors are adequately represented on the logit scale", "Separation is absent or handled"],
    failureModes: ["Complete separation", "Too few outcome events", "Uncalibrated predictions", "Post-hoc variable selection", "Odds ratios described as risk ratios"],
    alternatives: ["Penalized logistic regression", "Firth logistic regression", "Mixed-effects logistic regression"],
    validation: ["Check separation and convergence", "Inspect calibration", "Use held-out validation for prediction claims"],
    officialDocumentation: "https://stat.ethz.ch/R-manual/R-devel/library/stats/html/glm.html",
  },
  {
    slug: "principal-component-analysis",
    name: "Principal component analysis",
    package: "stats",
    fn: "prcomp",
    category: "Exploratory analysis",
    status: "VERIFIED",
    origin: "BUILT_IN",
    question: "Which orthogonal directions explain the greatest variance in a centered, optionally scaled feature matrix?",
    notAnswered: ["Differential expression", "Causality", "Whether visible clusters are statistically distinct"],
    appropriate: ["Exploratory sample structure and quality assessment", "Numeric matrices with documented transformation and scaling"],
    assumptions: ["Euclidean variance is meaningful", "Centering and scaling choices are appropriate", "Missing data are handled before fitting"],
    failureModes: ["Dominance by library size or scale", "Overinterpreting clusters", "Using outcome labels to select displayed components", "Ignoring outliers"],
    alternatives: ["Multidimensional scaling", "Robust PCA", "UMAP for visualization with different objectives"],
    validation: ["Record transformation, center, and scale", "Inspect variance explained and loadings", "Repeat after relevant quality-control exclusions"],
    officialDocumentation: "https://stat.ethz.ch/R-manual/R-devel/library/stats/html/prcomp.html",
  },
];

export const builtInMethods: MethodCard[] = methods.map((method) => ({
  ...method,
  origin: method.origin ?? "BUILT_IN",
}));

export const provenanceEvents = [
  { time: "09:42:16", type: "DATA_REGISTERED", title: "Synthetic_Cohort registered", detail: "Dataset hash sha256:8fb2…d91c", actor: "Researcher" },
  { time: "09:44:03", type: "DATA_FILTERED", title: "Sample selection applied", detail: "Rule: Tissue == Tissue_A · 120 synthetic samples retained", actor: "Execution engine" },
  { time: "09:44:06", type: "NORMALIZED", title: "TMM normalization completed", detail: "edgeR · normalization factors stored", actor: "Execution engine" },
  { time: "09:44:09", type: "MODEL_FITTED", title: "limma-voom model fitted", detail: "~ Exposure_A + Age + Sex + Technical_Batch", actor: "Execution engine" },
  { time: "09:44:10", type: "MULTIPLE_TESTING_APPLIED", title: "Benjamini–Hochberg FDR applied", detail: "Family: 12,000 retained synthetic features", actor: "Rule engine" },
  { time: "09:45:22", type: "GENE_SET_TESTED", title: "Four predefined gene sets tested", detail: "cameraPR · full signed statistic universe", actor: "Execution engine" },
  { time: "09:47:31", type: "CLAIM_CREATED", title: "Claim CLM-004 recorded", detail: "Classified as INFERENCE · caveat attached", actor: "Researcher" },
];

export const contextAllowed = [
  "Scientific question",
  "Approved variable roles",
  "Method and package names",
  "Analysis specification",
  "Sanitized result summary",
  "Rule-engine warnings",
  "Validation and provenance summaries",
];

export const contextBlocked = [
  "Raw count matrix",
  "Participant-level metadata",
  "Participant identifiers",
  "Uploaded file contents",
  "Raw expression values",
  "Sensitive filenames and hidden metadata",
];
